---
title: "Final literature review summary"
author: "Alex Lin "
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
bibliography: reference.bib
---

------------------------------------------------------------------------

# Summary

## 1. Literature Review

### new definition of heatwave: 2 thresholds (T1 and T2) and avg temp

According to [@t1t2]

-   definition:

    -   A heat wave was then defined as the longest period of consecutive days satisfying the following three conditions:

    (i) The daily maximum temperature must be above T1 for at least 3 days
    (ii) the average daily maximum temperature must be above T1 for the entire period
    (iii) the daily maximum temperature must be above T2 for every day of the entire period .

    -   Threshold 1 (T1) was defined as the 97.5th percentile of the distribution of maximum temperatures in the observations and in the simulated present-day climate (seasonal climatology at the given location), and T2 was defined as the 81st percentile. ds s ( R. Huth et al., Clim. Change 46, 29 (2000))

-   advantages:

    -   allowing analyses of heat wave **duration** and **frequency**.

-   association with atmospheric circulation patterns:

    -   Heat waves are generally associated with specific atmospheric circulation patterns represented by semistationary **500-hPa positive height anomalies** that dynamically produce subsidence, clear skies, light winds, warm-air advection, and prolonged hot conditions at the surface. (M. A. Palecki et al., Bull. Am. Meteorol. Soc. 82, 1353 (2001) K. E. Kunkel et al. Bull. Am. Meteorol. Soc. 77, 1507 (1996) )

### new definition of heatwave: Excess Heat Factor (EHF)

According to [@3def]

-   Definition:

    -   EHI(accl.) describes the anomaly over a 3-day window against the preceding 30 days

    -   EHI(sig.) describes the anomaly of the same window against an extreme threshold.

    -   it has been used to study the impacts of extreme heat events on human health and mortality

    -   From a purely climatological standpoint, the EHF index is the most appealing:

        -   Consider both Tmax and Tmin

        -   Conditions leading up to a given day (i.e., the previous two days) are also considered, which can therefore amplify or dampen heat wave amplitude

        -   Determine the anomaly against recent conditions by comparing mean of the preceding month.

        -   Identification of the similarity between intense regional heat waves and the meteorological phenomena that may drive them.(Pezza et al. 2012)

-   Other definition application

    -   Those in farming and **agriculture** may be more interested in Tmin-based heat waves, which can affect the growth and planting time of some crops (e.g., Peng et al. 2004; Liu et al. 2006; Lanning et al. 2011).

    -   Those in the **engineering industry** may only be interested in periods of consecutive extreme Tmax days, which may impact the integrity of human structures such as buildings, power, and transport networks (Colombo et al. 1999; Pezza et al. 2012).

    -   **Health experts**, however, may require a combination of periods of Tmin and Tmax and anomalies that consider relative conditions, as the capability for nighttime relief and adaptation can have a profound impact on excess **mortality and morbidity** (Karl and Knight 1997; Meehl and Tebaldi 2004; Hansen et al. 2008; PwC 2011).

<!-- -->

-   APPENDIX 1: Heat Wave Indices Determined Unsuitable by this Study (page 30/46)

    -   This indicates that using a **single absolute threshold** for a region where multiple climate regimes exist (such as Australia) cannot adequately represent heat wave occurrence across all such climates.

    -   This inference can also extend to other large regional or continental studies, such as over Europe, Asia, and the Americas where a broad range of climates exist

    -   Absolute thresholds are sometimes necessary from **an impacts perspective** (e.g., concerning plant physiology or human health), but from a climatological perspective, they may only be suitable when studying **heat waves in a small region or at a point source** (e.g., where an observation station is located) when a single climate regime exists.

-   [@potato-heat] suggested that the heatwave definition should be based on the local climate, so we will explore the local climate data to determine the best heatwave definition for the region.

-   Rationale for choosing potatoes: According to [@potato-heat], potatoes are highly vulnerable to high temperatures, which negatively impact tuber development, storage, and seed potato fitness. To investigate the potential correlation between temperature extremes, including heat waves, and long-term yield patterns in British Columbia, a comprehensive yield dataset is required. <br>

-   The ERA5 dataset has been widely utilized in numerous studies and publications, including notable examples such as @era5-steamflow and @2021-heatwave.

    ------------------------------------------------------------------------

# References
