---
title: "generalized extreme value (GEV) distribution for single variable "
author: "alex lin "
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---


<script>
function toggleCollapsible(section) {
  var content = section.nextElementSibling;
  if (content.style.display === "none") {
    content.style.display = "block";
  } else {
    content.style.display = "none";
  }
}
</script>



```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../R_model/GEV example (1)/gev.R") 
source("../R_model/read_data.R") 
source("../R_model/GEV_model.R") 

```


<h1 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>GEV for single variable</b>
</h1>
<div style="display:none;">  

</div>
<h2 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>FortNelson</b>
</h2>
<div style="display:none;">  


<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>maxEHF</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(ehf_ymax_wide, "fn","Annual MAX EHF")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b> avgexc</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(avgexc_ymax_wide, "fn","Annual MAX Avg Exc Temp")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>


</div>
<h2 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>YVR</b>
</h2>
<div style="display:none;">  


<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Assess trend for EHF </b>
</h3>
<div style="display:none;">  

```{r echo=FALSE, message=FALSE, warning=FALSE}
# What are better methods to assess trend?
ehf0609 = read.csv("../R_model/GEV example (1)/ehf0609.csv", header=T)

# Create the plot
ggplot(ehf0609, aes(x = year, y = yv)) +
  geom_point() +  # Plot the data points
  geom_smooth(method = "lm", formula = y ~ I((x - 1941) / 10), color = "blue") +  # Add the linear regression line
  labs(title = "Trend of YV Over Years",
       x = "Year",
       y = "YV") +
  theme_minimal()
# Example: LOESS smoothing
library(ggplot2)
ggplot(ehf0609, aes(x=year, y=yv)) + 
  geom_point() + 
  geom_smooth(method="loess")
# Example: Seasonal Decomposition
library(forecast)
decomposed = stl(ts(ehf0609$yv, frequency=12), s.window="periodic")
plot(decomposed)
```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>maxEHF</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(ehf_ymax_wide, "yv","Annual MAX EHF")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b> avgexc</b>
</h3>
<div style="display:none;"> 
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(avgexc_ymax_wide, "yv","Annual MAX Avg Exc Temp")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```



</div>

</div>
<h2 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Kelowna</b>
</h2>
<div style="display:none;">  


<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>maxEHF</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(ehf_ymax_wide, "ke","Annual MAX EHF")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b> avgexc</b>
</h3>
<div style="display:none;"> 
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(avgexc_ymax_wide, "ke","Annual MAX Avg Exc Temp")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```



</div>

</div>
<h2 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Abbotsford</b>
</h2>
<div style="display:none;">  


<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>maxEHF</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(ehf_ymax_wide, "ab","Annual MAX EHF")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b> avgexc</b>
</h3>
<div style="display:none;"> 
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(avgexc_ymax_wide, "ab","Annual MAX Avg Exc Temp")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```


</div>


</div>
<h2 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Prince George</b>
</h2>
<div style="display:none;">  


<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>maxEHF</b>
</h3>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(ehf_ymax_wide, "pg","Annual MAX EHF")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b> avgexc</b>
</h3>
<div style="display:none;"> 
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage
plots <- gev_analysis_plots(avgexc_ymax_wide, "pg","Annual MAX Avg Exc Temp")
print(plots$qq_plot)
print(plots$return_level_plot)
print(plots$tail_behavior_plot)

```



