---
title: "FAOSTAT"
author: "alex lin "
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---
<script>
function toggleCollapsible(section) {
  var content = section.nextElementSibling;
  if (content.style.display === "none") {
    content.style.display = "block";
  } else {
    content.style.display = "none";
  }
}
</script>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../R_agricultural/read_data.R")  ## read data
source("../R_agricultural/data_wrangling.R")  ## data wrangling
```
<h1 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Plot</b>
</h1>
<div style="display:none;">  

</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>EDA Plot for each crop data</b>
</h3>
<div style="display:none;">  
```{r}

plot_fao_data(data_fao)
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
# FILTER data_x to start from 1961 as it is the start of the FAO data
#LOCAL_DATE
data_x <- data_x %>%
  filter(LOCAL_DATE >= "1961-01-01")

weekly_data_x <- aggregate_data_week(data_x)
monthly_data_x <- aggregate_data_month(data_x)

```
</div>

<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>linear reg for yield VS EHF 95</b>
</h3>
<div style="display:none;">  
</div>

<h4 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Abbotsford weekly</b>
</h4>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage:
results <- perform_linear_regression_weekly(weekly_data_x, data_fao,"Abbotsford", "week_Mean_EHF_95")

unique_crops <- unique(data_fao$Item)
#Print results for each crop
for (crop in unique_crops) {
  print(paste("Results for crop:", crop))
  print(results[[crop]]$summary)
  if (!is.null(results[[crop]]$plot)) {
    print(results[[crop]]$plot)
  }
}

```

<h4 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Kelowna weekly</b>
</h4>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage:
results <- perform_linear_regression_weekly(weekly_data_x, data_fao,"Kelowna", "week_Mean_EHF_95")

unique_crops <- unique(data_fao$Item)
#Print results for each crop
for (crop in unique_crops) {
  print(paste("Results for crop:", crop))
  print(results[[crop]]$summary)
  if (!is.null(results[[crop]]$plot)) {
    print(results[[crop]]$plot)
  }
}

```

</div>

<h4 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Abbotsford monthly</b>
</h4>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage:
results <- perform_linear_regression_monthly(monthly_data_x, data_fao,"Abbotsford", "maxmon_EHF_95")

unique_crops <- unique(data_fao$Item)
#Print results for each crop
for (crop in unique_crops) {
  print(paste("Results for crop:", crop))
  print(results[[crop]]$summary)
  if (!is.null(results[[crop]]$plot)) {
    print(results[[crop]]$plot)
  }
}

```


</div>

<h4 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Abbotsford monthly</b>
</h4>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage:
results <- perform_linear_regression_monthly(monthly_data_x, data_fao,"Kelowna", "maxmon_EHF_95")

unique_crops <- unique(data_fao$Item)
#Print results for each crop
for (crop in unique_crops) {
  print(paste("Results for crop:", crop))
  print(results[[crop]]$summary)
  if (!is.null(results[[crop]]$plot)) {
    print(results[[crop]]$plot)
  }
  
  
  
}

```


</div>
<h3 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>linear reg for yield VS daily Max Temp</b>
</h3>
<div style="display:none;">  
</div>

<h4 onclick="toggleCollapsible(this);">
<!--TEXT SHOWS: -->
<b>Abbotsford</b>
</h4>
<div style="display:none;">  
```{r echo=FALSE, message=FALSE, warning=FALSE}
# Example usage:
results <- perform_linear_regression_weekly(weekly_data_x, data_fao,"Abbotsford", "week_Mean_Temperature")

unique_crops <- unique(data_fao$Item)
#Print results for each crop
for (crop in unique_crops) {
  print(paste("Results for crop:", crop))
  print(results[[crop]]$summary)
  if (!is.null(results[[crop]]$plot)) {
    print(results[[crop]]$plot)
  }
}

```




```{r echo=FALSE, message=FALSE, warning=FALSE}
# Summarize the data by Crop_Type to get the year range
crop_year<- data_statcan_crop %>%
  group_by(Crop_Type) %>%
  summarize(Start_Year = min(REF_DATE), End_Year = max(REF_DATE))
crop_year

```





```{r echo=FALSE, message=FALSE, warning=FALSE,fig.width=17, fig.height=9}
# Summarize production by year and crop type
# Plot the data
ggplot(data_statcan_crop, aes(x = REF_DATE, y = Production, color = Crop_Type)) +
  geom_line() +
  geom_point() +
  labs(title = "Production of Crops over Time",
       x = "Year",
       y = "Production",
       color = "Crop Type") +
  theme_minimal() +
  facet_wrap(~GEO)
```






```{r echo=FALSE, message=FALSE, warning=FALSE,fig.width=17, fig.height=9}

# Summarize the data by Crop_Type to get the year range
fruit_year<- data_statcan_fruit %>%
  group_by(Crop_Type) %>%
  summarize(Start_Year = min(REF_DATE), End_Year = max(REF_DATE))

#order by Start_Year
fruit_year <- fruit_year[order(fruit_year$Start_Year),]
fruit_year
```




```{r echo=FALSE, message=FALSE, warning=FALSE,fig.width=17, fig.height=9}
# Summarize production by year and crop type
# Plot the data
ggplot(data_statcan_fruit, aes(x = REF_DATE, y = Production, color = Crop_Type)) +
  geom_line() +
  geom_point() +
  labs(title = "Production of Crops over Time",
       x = "Year",
       y = "Production",
       color = "Crop Type") +
  theme_minimal() 

data_statcan_fruit_zoomed <- data_statcan_fruit %>%
  filter(Production <= 50000)

# Plot the data
ggplot(data_statcan_fruit_zoomed, aes(x = REF_DATE, y = Production, color = Crop_Type)) +
  geom_line() +
  geom_point() +
  labs(title = "Production of Crops over Time",
       x = "Year",
       y = "Production",
       color = "Crop Type") +
  theme_minimal() 
```



```{r echo=FALSE, message=FALSE, warning=FALSE,fig.width=17, fig.height=9}
# Summarize production by year and crop type
# Plot the data

#filter REF_DATE to 2011-2019
data_statcan_fruit_com <- data_statcan_fruit %>%
  filter(REF_DATE >= "2011" & REF_DATE <= "2019")

ggplot(data_statcan_fruit_com, aes(x = REF_DATE, y = Production, color  = interaction(Estimates, Crop_Type))) +
  geom_line() +
  geom_point() +
  labs(title = "Production of Crops over Time",
       x = "Year",
       y = "Production",
       color = "Crop Type") +
  theme_minimal() 

#filter Production less than 15000
data_statcan_fruit_less <- data_statcan_fruit_com %>%
  filter(Production <= 15000)

#for loop of Crop_Type to plot
for (i in unique(data_statcan_fruit_less$Crop_Type)){
  p <- ggplot(data_statcan_fruit_less %>% filter(Crop_Type == i), aes(x = REF_DATE, y = Production, color  = (Estimates))) +
    geom_line() +
    geom_point() +
    labs(title = paste("Production of Crops over Time for", i),
         x = "Year",
         y = "Production",
         color = "Crop Type") +
    theme_minimal() 
  print(p)
}



#filter Production less than 15000
data_statcan_fruit_more <- data_statcan_fruit_com %>%
  filter(Production > 10000)
ggplot(data_statcan_fruit_more , aes(x = REF_DATE, y = Production,  color  = interaction(Estimates, Crop_Type))) +
    geom_line() +
    geom_point() +
    labs(title = paste("Production of Crops over Time"),
         x = "Year",
         y = "Production",
         color = "Crop Type") +
    theme_minimal() 

```



